// The ONLY point of contact between TramSystem's synchronized shared observer and Epic's
// nDisplay/DisplayCluster rendering system. nDisplay owns physical screen/window/viewport
// topology (authored via its own Configurator tool - see SETUP.md - not generated by this
// plugin); TramSystem owns tram simulation and the shared observer transform (ATramViewRig, in
// the core module). This component's entire job is to move nDisplay's "stage"
// (ADisplayClusterRootActor, which owns the screen/viewport component hierarchy in its own
// local space) to match ATramViewRig::GetSharedObserverTransform() every frame - conceptually
// identical to how ATramSlotPreviewCamera and UTramMovementComponent already move an actor to
// match a computed transform each tick, just applied to nDisplay's root actor instead of a
// camera or the tram mesh.
//
// Deliberately isolated into its own module (see TramSystemDisplayCluster.Build.cs) so a
// project that doesn't use nDisplay never needs to reference this at all, and the core
// TramSystem module never depends on DisplayCluster (Objective 19).
//
// IMPORTANT: written from general knowledge of nDisplay's stable public API (ADisplayClusterRootActor
// has been the root-actor class since nDisplay's UE4 days) without access to an Unreal Engine
// 5.7 installation to verify compilation - see the module's top-level comment. If this does
// not compile against your engine version, the DisplayCluster module's actual headers are the
// source of truth; the logic here (read a transform, apply it via the ordinary AActor API) is
// intentionally the simplest possible integration, so a fix should only need to touch how the
// root actor is found/moved, not the rest of this module or anything in core TramSystem.
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "TramDisplayClusterViewSync.generated.h"

class ATramViewRig;
class ADisplayClusterRootActor;

UCLASS(ClassGroup = (Tram), meta = (BlueprintSpawnableComponent))
class TRAMSYSTEMDISPLAYCLUSTER_API UTramDisplayClusterViewSync : public UActorComponent
{
	GENERATED_BODY()

public:
	UTramDisplayClusterViewSync();

	UPROPERTY(EditInstanceOnly, BlueprintReadOnly, Category = "Tram|DisplayCluster")
	TObjectPtr<ATramViewRig> ViewRig;

	// Left unset, auto-resolved in BeginPlay (there is normally exactly one root actor per
	// nDisplay node/process).
	UPROPERTY(EditInstanceOnly, BlueprintReadOnly, Category = "Tram|DisplayCluster")
	TObjectPtr<ADisplayClusterRootActor> RootActor;

protected:
	virtual void BeginPlay() override;
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;
};
