// The ONLY point of contact between TramSystem's synchronized shared observer and Epic's
// nDisplay/DisplayCluster rendering system. nDisplay owns physical screen/window/viewport
// topology (authored via its own Configurator tool - see SETUP.md - not generated by this
// plugin); TramSystem owns tram simulation and the shared observer transform (ATramViewRig, in
// the core module). This component's entire job is to move nDisplay's "stage"
// (ADisplayClusterRootActor, which owns the screen/viewport component hierarchy in its own
// local space) to match ATramViewRig::GetSharedObserverTransform() every frame - conceptually
// identical to how ATramSlotPreviewCamera and UTramMovementComponent already move an actor to
// match a computed transform each tick, just applied to nDisplay's root actor instead of a
// camera or the tram mesh.
//
// Deliberately isolated into its own plugin (TramSystemDisplayCluster.uplugin, separate from
// TramSystem.uplugin - see that file's Build.cs comment for why a second module alone wasn't
// enough) so a project that doesn't use nDisplay never needs to enable this at all, and the
// core TramSystem plugin never depends on DisplayCluster (Objective 19).
//
// IMPORTANT: written from general knowledge of nDisplay's stable public API (ADisplayClusterRootActor
// has been the root-actor class since nDisplay's UE4 days) without access to an Unreal Engine
// 5.7 installation to verify compilation - see the module's top-level comment. If this does
// not compile against your engine version, the DisplayCluster module's actual headers are the
// source of truth; the logic here (read a transform, apply it via the ordinary AActor API) is
// intentionally the simplest possible integration, so a fix should only need to touch how the
// root actor is found/moved, not the rest of this module or anything in core TramSystem.
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "TramDisplayClusterViewSync.generated.h"

class ATramViewRig;
class ADisplayClusterRootActor;

UCLASS(ClassGroup = (Tram), meta = (BlueprintSpawnableComponent))
class TRAMSYSTEMDISPLAYCLUSTER_API UTramDisplayClusterViewSync : public UActorComponent
{
	GENERATED_BODY()

public:
	UTramDisplayClusterViewSync();

	UPROPERTY(EditInstanceOnly, BlueprintReadOnly, Category = "Tram|DisplayCluster")
	TObjectPtr<ATramViewRig> ViewRig;

	// Recommended: set this explicitly to your level's stage/root actor rather than leaving it
	// unset. BeginPlay can auto-resolve it via a level-wide class search, but only when there
	// is exactly one ADisplayClusterRootActor-satisfying actor in the level - it logs a warning
	// naming every candidate (rather than guessing) if it finds more than one, e.g. because
	// more than one nDisplay config asset is placed in the level. A root actor's name in the
	// World Outliner is not a reliable way to identify it - verify by class, not name (see
	// SETUP.md 7a).
	UPROPERTY(EditInstanceOnly, BlueprintReadOnly, Category = "Tram|DisplayCluster")
	TObjectPtr<ADisplayClusterRootActor> RootActor;

	// How often (seconds) to log the root actor's current transform, purely so successful
	// operation is visible/confirmable in the Output Log rather than only inferable from the
	// absence of the BeginPlay failure warnings. 0 disables periodic logging entirely.
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tram|DisplayCluster", meta = (ClampMin = "0.0"))
	float DiagnosticLogIntervalSeconds = 2.f;

protected:
	virtual void BeginPlay() override;
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

private:
	double TimeSinceLastDiagnosticLog = 0.0;
};
